[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'

solc_version = '0.8.7'
optimizer = false
via_ir = false
verbosity = 3

# ignore solc warnings for missing license
ignored_error_codes = [1878]
gas_price = 1

path_pattern = 'test/Socket.t.sol'

[profile.prod]
optimizer = true
optimizer_runs = 200
via_ir = false


# See more config options https://github.com/gakonst/foundry/tree/master/config
